name: GCC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install GCC req
      run: sudo apt install build-essential manpages-dev

    - name: Build
      # Build your program with the given configuration
      run: gcc main.cpp
      
